services:
  frontend:
    container_name: frontend
    build: ./FRONTEND
    ports:
      - "7777:7777"
    depends_on:
      - backend
    restart: always
    networks:
      - appnet

  backend:
    container_name: backend
    build:
      context: ./BACKEND
      target: ${BUILD_TARGET:-production} # selects the correct Dockerfile stage
    ports:
      - "8070:8070" # Http
      - "8071:8071" # WebSocket
      - "8072:8072" # Ingestion Port
    restart: always
    networks:
      - appnet
    volumes:
      - ./BACKEND/public:/app/public
    env_file:
      - ./BACKEND/.env
    environment:
      ENV: ${ENV:-production}
      NODE_ENV: ${ENV:-production}

  device-simulator:
    container_name: device-simulator
    build: ./DEVICE_SIMULATOR
    depends_on:
      - backend
    restart: always
    networks:
      - appnet
    environment:
      INGEST_HOST: http://backend

networks:
  appnet:
